name: Test
on:
  pull_request:
    paths: ['excellent/*.rb']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: bundle exec rspec
